//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comapny_Registration
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Certificate_Number { get; set; }
        public string Email { get; set; }
        public decimal Phone_Number { get; set; }
        public string Password { get; set; }
        public string CPassword { get; set; }
        public string City { get; set; }
    }
}
