//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities2 : DbContext
    {
        public Database1Entities2()
            : base("name=Database1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apply_Job> Apply_Job { get; set; }
        public virtual DbSet<Comapny_Registration> Comapny_Registration { get; set; }
        public virtual DbSet<Company_Details> Company_Details { get; set; }
        public virtual DbSet<Mem_Tab> Mem_Tab { get; set; }
        public virtual DbSet<Post_Job> Post_Job { get; set; }
        public virtual DbSet<Resume> Resumes { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Trainer_Details> Trainer_Details { get; set; }
    }
}
