//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_Job
    {
        public int Id { get; set; }
        public string Comapany_Name { get; set; }
        public string Job_Descripation { get; set; }
        public string Requirements { get; set; }
        public decimal Salary { get; set; }
        public decimal Contact_Info { get; set; }
        public string Email { get; set; }
        public string Require_Qualification { get; set; }
    }
}
