//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        public int Id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Phone_No { get; set; }
        public string Gender { get; set; }
        public string Qulification { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Expertisy { get; set; }
        public string Experince { get; set; }
        public string ExtraSkills { get; set; }
        public string Email { get; set; }
    }
}
