//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Batch_Id { get; set; }
        public string Batch_Name { get; set; }
        public string Batch_Date { get; set; }
        public string Batch_Time { get; set; }
        public string Subject { get; set; }
        public string Trainer_Name { get; set; }
        public string Student_Name { get; set; }
    }
}
