//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer_Details
    {
        public int TId { get; set; }
        public string TName { get; set; }
        public System.DateTime TDOB { get; set; }
        public System.DateTime TDateofjoin { get; set; }
        public string TSalary { get; set; }
        public string TQualification { get; set; }
        public string TSchedule { get; set; }
        public string TEmail { get; set; }
        public string TPWD { get; set; }
    }
}
